// <auto-generated />
using System;
using HeatFlow.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeatFlow.Infrastructure.Migrations
{
    [DbContext(typeof(HeatFlowDbContext))]
    [Migration("20260203232005_AddConfigurationChangeLog")]
    partial class AddConfigurationChangeLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeatFlow.Domain.BoilerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExecutionId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeederTime")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ForecastMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Mixer4DPosition")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomsHeatedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TempExternal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempReturn")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempTarget")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("BoilerState", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.ConfigurationChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.ToTable("ConfigurationChangeLog", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.ExecutionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionTime");

                    b.HasIndex("Phase");

                    b.ToTable("ExecutionHistory", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.ForecastDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentTemp")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ForecastHoursJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("TempDropThreshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempRiseThreshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("ForecastDataCache", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.HeatingParametersEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("BoilerNominalTemp")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("BoilerRetryCount")
                        .HasColumnType("int");

                    b.Property<decimal>("BoilerRetryDelay")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BoilerTempTolerance")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("BufferHeatingTime")
                        .HasColumnType("int");

                    b.Property<decimal>("BufferPreparation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BufferPreparationBase")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeficitHighP1")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeficitHighP1Base")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeficitHighP2")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeficitHighP2Base")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeficitHighP3")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DeficitHighP3Base")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FeederBoostMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FeederBoostThreshold")
                        .HasColumnType("int");

                    b.Property<decimal>("FeederEconomyMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("FeederEconomyThreshold")
                        .HasColumnType("int");

                    b.Property<decimal>("FeederNormalMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FeederTimeDefault")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FeederTimeTolerance")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ForecastHoursCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ForecastPreHeatingBufferMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastPreHeatingP1Multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastPreHeatingP2Multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastPreHeatingP3Multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastReductionBufferMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastReductionP1Multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastReductionP2Multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastReductionP3Multiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastTempDropThreshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ForecastTempRiseThreshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FrostCompensationFactor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Hysteresis")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HysteresisSafetyThreshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MaxValvesOpen")
                        .HasColumnType("int");

                    b.Property<decimal>("MinMixer4D")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinReturnTemp")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinTempDiff")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MinValvesOpen")
                        .HasColumnType("int");

                    b.Property<decimal>("Mixer4DDefault")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ScoreDeficitMultiplier")
                        .HasColumnType("int");

                    b.Property<int>("ScoreHeatingScheduleBonus")
                        .HasColumnType("int");

                    b.Property<int>("ScorePriorityMultiplier")
                        .HasColumnType("int");

                    b.Property<int>("ScoreSensitiveBonus")
                        .HasColumnType("int");

                    b.Property<int>("ScoreUsageSoonBonus")
                        .HasColumnType("int");

                    b.Property<decimal>("TempValidationMax")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempValidationMin")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageSoonMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ValveRetryCount")
                        .HasColumnType("int");

                    b.Property<decimal>("ValveRetryDelay")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ValveTolerance")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("HeatingParameters", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.RoomConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AutomationDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("HeatingSchedule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("Sensitive")
                        .HasColumnType("bit");

                    b.Property<string>("SensorTemperatureEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TempTarget")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempTargetActive")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempTargetInactive")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UsageSchedule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValveEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Name");

                    b.HasIndex("Name");

                    b.ToTable("RoomConfiguration", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.RoomState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<int>("ExecutionId")
                        .HasColumnType("int");

                    b.Property<bool>("HeatingEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TempActual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempDeficit")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempTarget")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("RoomName");

                    b.ToTable("RoomState", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BoilerTempEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EkoPiecDeviceSn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FeederTimeEntityId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Mixer4DPositionEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoomsList")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("SystemEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("TempReturnEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfiguration", (string)null);
                });

            modelBuilder.Entity("HeatFlow.Domain.ValveState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExecutionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TempActual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TempSet")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ValveEntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("RoomName");

                    b.ToTable("ValveState", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
